package detalcare;

dialect "mvel"

import java.util.LinkedList
import detalcare.model.*

global org.slf4j.Logger logger

// --------------------------------------------------------------

rule "tooth have pulp necrosis"
  when
    ToothTest(
      coloration == Coloration.brown || coloration == Coloration.gray,
      kindOfPains contains KindOfPain.intense && kindOfPains contains KindOfPain.acute && kindOfPains contains KindOfPain.located,
      coldStimulus == ColdStimulus.negative,
      heatStimulus == HeatStimulus.negative,
      electricalStimulation == ElectricalStimulation.negative,
      percussionStimulation == PercussionStimulation.positive,
      pulpState == PulpState.shattered
    )
  then
    insert(Diagnosis.pulpNecrosis)
end


rule "tooth have pulp hyperemia"
  when
    ToothTest(
      coloration == Coloration.normal,
      kindOfPains contains KindOfPain.intense && kindOfPains contains KindOfPain.located,
      coldStimulus == ColdStimulus.positive,
      heatStimulus == HeatStimulus.positive,
      electricalStimulation == ElectricalStimulation.positive,
      percussionStimulation == PercussionStimulation.negative,
      pulpState == PulpState.intact
    )
  then
    insert(Diagnosis.pulpHyperemia)
end


rule "tooth have hyperplastic pulpitis"
  when
    ToothTest(
      coloration == Coloration.reddish,
      kindOfPains contains KindOfPain.acute && kindOfPains contains KindOfPain.located,
      coldStimulus == ColdStimulus.positive,
      heatStimulus == HeatStimulus.negative,
      electricalStimulation == ElectricalStimulation.negative,
      percussionStimulation == PercussionStimulation.positive,
      pulpState == PulpState.hypertrophied,
      patientAge == PatientAge.young
    )
  then
    insert(Diagnosis.hyperplasticPulpitis)
end


rule "tooth have pulp atrophy"
  when
    ToothTest(
      coloration == Coloration.yellowish,
      kindOfPains contains KindOfPain.noPain,
      coldStimulus == ColdStimulus.negative,
      heatStimulus == HeatStimulus.negative,
      electricalStimulation == ElectricalStimulation.negative,
      percussionStimulation == PercussionStimulation.negative,
      pulpState == PulpState.atrophied,
      patientAge == PatientAge.oldMan
    )
  then
    insert(Diagnosis.pulpAtrophy)
end


rule "tooth have acute pulpitis serosa"
  when
    ToothTest(
      coloration == Coloration.normal,
      kindOfPains contains KindOfPain.spontaneous && kindOfPains contains KindOfPain.diffuse && kindOfPains contains KindOfPain.discontinuous,
      coldStimulus == ColdStimulus.positive,
      heatStimulus == HeatStimulus.positive,
      percussionStimulation == PercussionStimulation.positive,
      pulpState == PulpState.intact
    )
  then
    insert(Diagnosis.pulpitisSerosa)
end


rule "tooth have acute purulent pulpitis"
  when
    ToothTest(
      coloration == Coloration.normal,
      kindOfPains contains KindOfPain.spontaneous && kindOfPains contains KindOfPain.intense && kindOfPains contains KindOfPain.continuous && kindOfPains contains KindOfPain.located,
      coldStimulus == ColdStimulus.negative,
      heatStimulus == HeatStimulus.positive,
      percussionStimulation == PercussionStimulation.positive,
      pulpState == PulpState.partiallyDestroyed
    )
  then
    insert(Diagnosis.acutePurulentPulpitis)
end


rule "tooth have infiltrative pulpitis"
  when
    ToothTest(
      coloration == Coloration.normal,
      kindOfPains contains KindOfPain.spontaneous && kindOfPains contains KindOfPain.located && kindOfPains contains KindOfPain.continuous,
      coldStimulus == ColdStimulus.positive,
      heatStimulus == HeatStimulus.positive,
      electricalStimulation == ElectricalStimulation.positive,
      pulpState == PulpState.shattered
    )
  then
    insert(Diagnosis.infiltrativePulpitis)
end


rule "tooth have unknown diagnosis"
  when
    ToothTest()
  then
    insert(Diagnosis.unknown)
end



